debug: true
element: app
dataPath: /assets/data
imagePath: /assets/img
styling:
    css: 'html, body {
        color: white;
        background-color: #333;
        padding: 0;
        margin: 0;
    }'
    addToHead: true
